package com.appheader.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig greenArticleDaoConfig;

    private final GreenArticleDao greenArticleDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        greenArticleDaoConfig = daoConfigMap.get(GreenArticleDao.class).clone();
        greenArticleDaoConfig.initIdentityScope(type);

        greenArticleDao = new GreenArticleDao(greenArticleDaoConfig, this);

        registerDao(GreenArticle.class, greenArticleDao);
    }
    
    public void clear() {
        greenArticleDaoConfig.getIdentityScope().clear();
    }

    public GreenArticleDao getGreenArticleDao() {
        return greenArticleDao;
    }

}
